# Generated by Django 3.2.14 on 2022-10-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_confirmed_image_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('status',)},
        ),
    ]
