# Generated by Django 4.1 on 2022-09-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0008_alter_payhistory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payhistory",
            name="authority",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
