# Generated by Django 4.1 on 2022-08-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_room_options_remove_message_pending_read_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
