# Generated by Django 3.2.14 on 2022-10-02 16:59

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
