# Generated by Django 4.1 on 2022-08-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20220731_1257"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(default="asas"),
            preserve_default=False,
        ),
    ]
